config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :blogs

  resources :users

  resources :categories

  root to: 'blogs#new' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

	belongs_to :category

	validates :title,  :content, :category_id, presence: true

end

app/models/category.rb
class Category < ApplicationRecord

	has_many :blogs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable , :validatable
  

       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


	before_action :authenticate_user!


	protect_from_forgery

    add_flash_types :danger, :info, :success, :warning

	def current_or_guest_user
    if current_user
      if session[:guest_user_id]  != current_user.id
        logging_in

        guest_user(with_retry = false).try(:reload).try(:destroy)
        session[:guest_user_id] = nil
      end
      current_user
    else
      guest_user
    end
  end

def current_user
  super || guest_user
end

def guest_user(with_retry = true)
 @cached_guest_user = User.find( session[:guest_user_id] ||= create_guest_user)
  rescue ActiveRecord::RecordNotFound #
     session[:guest_user_id] = nil
     guest_user if with_retry
end


private
def create_guest_user
  @user = User.create(:password => "guest", :email => "guest_#{Time.now.to_i}#{rand(99)}@gmail.com", guest: true)
  @user.save(:validate => false)
  session[:guest_user_id]= @user.id
end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

    before_action :set_blog, only: [:show, :edit, :update, :destroy]

    def index
        @blogs = Blog.all.paginate(page: params[:page], per_page: 5)
    end

    def new
        @blog = Blog.new
       @categories = Category.all.map { |c| [c.name, c.id]}
    end

    def create
        @blog = Blog.new(blog_params)
        if @blog.save
            flash[:info]="Blog created sucessfully"
           redirect_to blogs_path  
        else
         flash[:warning] ='invalid title && content && Category'
         redirect_to 'new_blog_path'
        end
    end

    def show
      
    end
    
    def edit
         @categories = Category.all.map { |c| [c.name, c.id]}
    end
    def update
        if @blog.update(blog_params)
         redirect_to blogs_path
        else
          render 'edit' 
        end 
    end

    def destroy
        @blog.destroy
        redirect_to blogs_path
    end

    private
    def blog_params
        params.require(:blog).permit(:title, :content, :author, :category_id)
    end

    def set_blog
        @blog = Blog.find(params[:id])
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def index
		@categories = Category.all
	end

	def show 
		@category = Category.find(params[:id])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def destroy
	@user = User.find(session[:guest_user_id])
	session.delete(:guest_user_id)
	redirect_to   new_user_session_path
end 
end

app/helpers/application_helper.rb
module ApplicationHelper

	def markdown(text)
       Redcarpet.new(text).to_html.html_safe
	end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/edit.html.erb
<%= form_for @blog, local: true do |f| %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %> <br>
  </div>

<div class="field">
 <%= f.label :content %>
 <%= f.text_area :content %> 
</div>

<div class="field">
  <%= f.label :author %>
  <%= f.text_field :author %>
</div>


<div class="field">
  <%= f.label :categories %>
  <%= f.select(:category_id, options_for_select(@categories), prompt: 'select one') %>
</div>

<%= f.submit %>

<% end %>

app/views/blogs/index.html.erb
<div style="margin-left: 250px; margin-top: 50px;">
<%= will_paginate @blogs %>
<% @blogs.each do |blog| %>
</div>
 <div class="posts", style="margin-left: 250px; margin-right: 250px; margin-top: 100px; ">
  <h4> <%= blog.title %> </h4>

     <%= markdown(blog.content) %> 
<li> <%= blog.author %> </li>


  
<li> <%= link_to Category.find(blog.category_id).name, category_path(blog.category_id) if blog.category_id.present? %></li>


 <%= link_to "Edit", edit_blog_path(blog) %>

 <%= link_to "delete", blog_path(blog), method: :delete, data: { confirm: "Are u sure do want to delete this blog"} %>


</div>





<% end %>

app/views/blogs/new.html.erb
<%= form_for @blog, local: true do |f| %>
<div style="margin-left: 150px;">
  <div class="form-group">
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %> <br>
  </div>
</div>

 <div class="form-group">
<div class="field">
 <%= f.label :content %>
 <%= f.text_area :content %> 
</div>
</div>

<div class="form-group">
<div class="field">
  <%= f.label :author %>
  <%= f.text_field :author %>
</div>
</div>

<div class="form-group">
<div class="field">
  <%= f.label :categories %>
  <%= f.select(:category_id, options_for_select(@categories), prompt: 'select one') %>
</div>
</div>

<%= f.submit %>

<% end %>

app/views/categories/index.html.erb
<div style="margin-left: 150px; margin-top: 50px;">
<% @categories.each do |category| %>

<li> <%= link_to category.name,category_path(category.id) %> </li>

<% end %>
</div>

app/views/categories/show.html.erb
<% blogs = Blog.where(category_id: params[:id]) %>
<div style="margin-top: 10px; margin-left: 250px; font-size: 20px; font-style: italic; color: grey;">
<%= @category.name %>
</div>
<% if blogs.present? %>
<% blogs.each do |blog| %>
<div style="margin-left: 250px; margin-right: 250px; margin-top: 50px;">
 <h6> <%= blog.title %> </h6>
<p style="font-style: italic;"> <%= blog.content %> </p>
</div>
<% end %>
<% else %>
 <p style= "margin-left: 250px; margin-right: 250px; margin-top: 50px; font-style: italic;"> There is no blog for this categories <%= link_to 'Create new blog', new_blog_path %> </p> 


<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <p class="navbar-text float-right"> 
      <% if user_signed_in? %>
         logged in as <strong> <%= current_user.email %>
      <%= link_to "Edit profile",  edit_user_registration_path, class: 'navbar-link' %>
      <% if current_user.present? %>
       <%= link_to "logout", destroy_user_session_path, method: :delete, class: 'navbar-link' %>
      <% else %>
      <%= link_to "logout", user_path(current_user.id), method: :delete, class: 'navbar-link' %>
      <% end %>
      <% else %>
      <%= link_to "Sign up", new_user_registration_path, class: 'navbar-link' %>
       <%= link_to "Login", new_user_session_path, class: 'navbar-link'  %>
       <% end %>

      <p class ="navbar-text", style="margin-left: 250px; margin-top: 20px;">
         <% if user_signed_in? %>
      
      <%= link_to "Blogs", blogs_path, class: 'navbar-link' %>
      <%= link_to "New Blog", new_blog_path, class: 'navbar-link' %>
      <%= link_to "Categories", categories_path, class: 'navbar-link' %>
       <% end %>

       
      <% flash.each do |key, msg| %>
      <div class="alert alert-<%= key %>">
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1> Hello welcome to the blog </h1>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>